### ISSUE TITLE
Proven success with JLCPCB and PCBWay?

### ISSUE THREAD

**Issue by Quas7** [abal1000x/emmc_adapter#1]
Hi abal1000x,

thanks for doing this layout!
May I ask, if you ordered the latest revision successfully from JLCPCB or PCBWay?
I just started the ordering from JLCPCB as they seem to be the better fit from their capability list with 1mm FR4 with all the cheapest options.

**Comment by abal1000x** [comment]
I use JLCPCB because its cheaper.

I use it and works. But i warn that installing this adapter is not as easy as flex method.

PCBWay usually have a better quality, but you need to calculate the price wisely.

**Comment by Quas7** [comment]
Yeah, but much more reliable than the flex for sure. I have now JLCPCB on my desk.

Balling the adapter on both sides is a bit tedious. I will likely only ball the adapter on the PCB side and ball the eMMC as usual.

Noticed, that the purple solder stop is not as robust as the green. Or it is just a batch issue.
