### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by r3nfolly** [abal1000x/emmc_adapter#2]
sorry for my ignorance, VDDF?
I know the A, C and D points, VDDF is the 3.3v?

Thanks for the project, saved me a lot of work/money

**Comment by abal1000x** [comment]
Yes it is.

But in practical i don't use it. I use the bigger pad on the mainboard pcb.
Its for a plan b, if i indeed need it, somehow.

**Comment by r3nfolly** [comment]
Thank you

**Comment by laleeroy** [comment]
> Thank you

Sorry for replying to this closed issue, but have you tried the gerber files? If so what is the thickness option you chose when ordering the PCB?
